### ISSUE TITLE
Problem with run() function in tutorial

### ISSUE THREAD

**Issue by FerRacimo** [bodkan/spammr#1]
When I use the function run() as written in the spammr tutorial in the section "Running the simulation", it successfully launches SLiM, but SLiM then throws off an error at line 108 of the simulation script ("add_markers(i);"). The error is  "ERROR (EidosValue_Float_singleton::IntAtIndex): INF cannot be converted to integer type".

**Comment by bodkan** [comment]
I first typed out a series of super long debugging instructions, then it hit me where the problem is. :)

In adding the ancestry tracking functionality, I did not properly take of the situation when the ancestry tracking is off. Or rather, it worked at first, but I broke it when I changed how user specifies whether to track ancestry or not. Briefly, the ancestry markers are distributed along each simulated genome in regular intervals determined by the number of ancestry markers... Well, if no tracking happens, then no markers are added, and SLiM was dividing by 0, yielding an ∞ value "INF" :)

The fix is [trivial](https://github.com/bodkan/spammr/commit/632cecf88bd3207cc53bac71f26f436880cc6138) and you can get it by running `git pull` from wherever you downloaded the package source on your machine.

Now running this (`ancestry_markers = 0` by default when not specified):

```
run(
  model_dir = "~/Desktop/test-model",
  gen_time = 30, burnin = 200, sim_length = 70000,
  seq_length = 100, recomb_rate = 0,
  interaction = 30, spread = 20
)
```

and this (notice `ancestry_markers = 1` - just one marker, for instance)

```
run(
  model_dir = "~/Desktop/test-model",
  gen_time = 30, burnin = 200, sim_length = 70000,
  seq_length = 100, recomb_rate = 0,
  interaction = 30, spread = 20, ancestry_markers = 1
)
```

should both work as written in the tutorial. At least I hope so - please let me know when you get around to testing this again.

Again, thanks a lot for trying this out and for your patience!

**Comment by FerRacimo** [comment]
Yes, that fixed it!
